// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AddSupport: typeof import('./src/components/AddSupport.vue')['default']
    AppMenu: typeof import('./src/components/app/AppMenu.vue')['default']
    EditProfile: typeof import('./src/components/EditProfile.vue')['default']
    Footer: typeof import('./src/components/app/Footer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Submenu: typeof import('./src/components/app/Submenu.vue')['default']
    Topbar: typeof import('./src/components/app/Topbar.vue')['default']
  }
}
